apiVersion: v1
kind: Service
metadata:
  name: pd-client
spec:
  type: LoadBalancer
  ports:
    - name: pd-client
      port: 12379
      protocol: TCP
      targetPort: 12379
  selector:
    app: placement-driver
---
apiVersion: v1
kind: Service
metadata:
  name: pd
  namespace: placement-driver
  labels:
    app: placement-driver
spec:
  clusterIP: None
  ports:
    - port: 12379
      name: client
    - port: 12380
      name: peer
  selector:
    app: placement-driver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pd
  namespace: placement-driver
  labels:
    app: placement-driver
spec:
  selector:
    matchLabels:
      app: placement-driver
  serviceName: "pd"
  replicas: 3
  template:
    metadata:
      name: placement-driver
      labels:
        app: placement-driver
    spec:
      securityContext:
        fsGroup: 65535
      containers:
        - name: placement-driver
          image: 716469478206.dkr.ecr.ap-northeast-1.amazonaws.com/placement-driver:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 12379
              name: client
            - containerPort: 12380
              name: peer
          volumeMounts:
            - name: pd-data
              mountPath: /data/placement-driver
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PD_PEERURLS
              value: "http://0.0.0.0:12380"
            - name: PD_CLIENTURLS
              value: "http://0.0.0.0:12379"
            - name: PD_ADVERTISEPEERURLS
              value: "http://$(NAME).pd:12380"
            - name: PD_ADVERTISECLIENTURLS
              value: "http://$(NAME).pd:12379"
            - name: PD_NAME
              value: "$(NAME)"
            - name: PD_DATADIR
              value: "/data/placement-driver/default.$(NAME)"
            - name: PD_INITIALCLUSTER
              value: "pd-0=http://pd-0.pd:12380,pd-1=http://pd-1.pd:12380,pd-2=http://pd-2.pd:12380"
            - name: PD_PDADDR
              value: "0.0.0.0:12378"
            - name: PD_ADVERTISEPDADDR
              value: "$(NAME).pd:12378"
            - name: PD_ETCD_INITIALCLUSTERTOKEN
              value: "pd-cluster"
  volumeClaimTemplates:
    - metadata:
        name: pd-data
      spec:
        storageClassName: gp2
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
