name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: ["master", "develop"]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      rust: ${{ steps.filter.outputs.rust }}
      pd: ${{ steps.filter.outputs.pd }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            java:
              - '.github/workflows/**'
              - 'sdks/frontend-java/**'
              - 'components/protocol/fbs/*.fbs'
            rust:
              - '.github/workflows/**'
              - 'range-server/**'
              - 'components/**'
              - 'sdks/frontend-rs/**'
            pd:
              - '.github/workflows/**'
              - 'pd/**'
              - 'components/protocol/fbs/rpc.fbs'
  java-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.java == 'true' }}
    uses: ./.github/workflows/java_build.yml
  rust-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.rust == 'true' }}
    uses: ./.github/workflows/rust_build.yml
  pd-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.pd == 'true' }}
    uses: ./.github/workflows/pd_build.yml
  build-result:
    runs-on: ubuntu-latest
    needs: [java-build, rust-build, pd-build]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect build result
        run: |
          if echo java-${{ needs.java-build.result }},rust-${{ needs.rust-build.result }},pd-${{ needs.pd-build.result }} | grep -E 'cancelled|failure' -o > null
          then
            echo "There are failed/cancelled builds"
            exit 1
          else
            echo "All builds are successful/skipped"
            exit 0
          fi
