name: Deploy doc site
on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**'
      - 'site/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'site/**'

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          dir: site
          cmd: install
      - name: build doc site
        uses: borales/actions-yarn@v4
        with:
          dir: site
          cmd: build
      - name: deploy to staging
        uses: amondnet/vercel-action@v25
        id: vercel-action-staging
        if: github.event_name == 'pull_request'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: true
          working-directory: site/build
      - name: deploy to production
        uses: amondnet/vercel-action@v25
        id: vercel-action-production
        if: github.event_name == 'push'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          scope: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: site/build
          github-comment: true
          vercel-args: '--prod '
