name: Nightly Build
on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  pd-images:
    name: Build and Push Placement Driver Images
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: ./pd
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./pd/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pd-nightly-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pd-nightly-
            ${{matrix.platform}}-${{matrix.go-version}}-pd-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elasticstream
          password: ${{ secrets.DOCKERHUB_READ_WRITE_TOKEN }}
      - name: Build and Push Nightly Images
        run: make manifest-list GO_VERSION=${{ matrix.go-version }} VERSION=nightly ALL_PLATFORMS=linux/amd64
