name: Placement Driver - CI

on:
  workflow_call:
permissions: read-all

defaults:
  run:
    working-directory: ./pd

jobs:
  flatc:
    name: Verify Flatbuffers
    strategy:
      matrix:
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install flatc
        run: |
          sudo ../scripts/try_install_flatc.sh
      - name: Verify Flatbuffers
        run: |
          make flatc
          git diff --exit-code
  lint:
    name: Lint
    strategy:
      matrix:
        go-version: [ "1.21" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./pd/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pd-lint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pd-lint-
            ${{matrix.platform}}-${{matrix.go-version}}-pd-
      - name: Install flatc
        run: |
          sudo ../scripts/try_install_flatc.sh
      - name: Lint
        run: make lint GO_VERSION=${{ matrix.go-version }}
  crossbuild:
    name: Cross Build
    strategy:
      matrix:
        go-version: [ "1.20", "1.21" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./pd/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pd-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pd-build-
            ${{matrix.platform}}-${{matrix.go-version}}-pd-
      - name: Install flatc
        run: |
          sudo ../scripts/try_install_flatc.sh
      - name: Build containers
        run: make all-container GO_VERSION=${{ matrix.go-version }}
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ "1.20", "1.21" ]
        platform: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./pd/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pd-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pd-test-
            ${{matrix.platform}}-${{matrix.go-version}}-pd-
      - name: Install flatc
        run: |
          sudo ../scripts/try_install_flatc.sh
      - name: Test
        run: make test GOFLAGS="-v" GO_VERSION=${{ matrix.go-version }} GO_TEST_FLAGS="-coverprofile=covprofile -covermode=atomic -coverpkg=./..."
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./pd/covprofile
          fail_ci_if_error: true
          verbose: true
          version: "v0.1.15"
