name: Release

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  release:
    name: Release with Debian Packages
    strategy:
      matrix:
        go-version: [ "1.20" ]
        platform: [ "ubuntu-22.04" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: ./pd/.go/cache
          key: ${{matrix.platform}}-${{matrix.go-version}}-pd-release-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{matrix.platform}}-${{matrix.go-version}}-pd-release-
            ${{matrix.platform}}-${{matrix.go-version}}-pd-
      - name: Build Placement Driver Debian Packages
        working-directory: ./pd
        run: make all-deb GO_VERSION=${{ matrix.go-version }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.4.0
        with:
          prefix-key: ""
          env-vars: ""
      - name: Install Deps
        run: |
          ./scripts/install_deps.sh
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Build Range Server Debian Packages
        run: |
          make all-deb PROFILE=release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          files: |
            ./dist/*.deb
            ./pd/distribution/*.deb
